### ISSUE TITLE
problem with the sample config file

### ISSUE THREAD

**Issue by Thomieh73** [mstrosaker/fragrecruit#1]
Hi,
I have tried your tool to generate a recruitement figure. I hope you have a little bit of time to help me here.
The script it is not working. When I run the command:

./fragrecruit-master/fragplot -o K1T0_subset -m 240 -i 70 -b 1000000 -l 100000 sample.config 

I get the following error message:

Processing reference genome: Bacillus anthracis strain K1
Traceback (most recent call last):
  File "./fragrecruit-master/fragplot", line 326, in <module>
    contigs.append([seq.name.split('|')[3], len(seq.seq)])
IndexError: list index out of range

I am not entirely sure what is happeninh here,
but I can see it has to do with the importing of the reference genome.

So in my sample.config file I have created the following blocks
refgenomes = [
    (
        "Bacillus anthracis strain K1",
        "28130",
        "bacillus_anthracis_strain_k1_final_asm.fasta"
    )
]

samples = [
    (
        "sample 1 (f, 31)",
        {
            "28130": "test.sam"
        }
    )
]

My genome has 38 contigs if I am right.
I create the sam file using the command:

bwa mem bacillus_anthracis_strain_k1_final_asm.fasta K1T0.pair_1.fastq K1T0.pair_2.fastq > test.sam

Note that the fastq files are only a small subset of a large metagenomic dataset? I check if the reads had the MD field, and some of them have it, but not all.

Any ideas what goes wrong in my analysis here.

**Comment by tvtv195** [comment]
Hi Tommieh73,
I ran the script and got the same error:

fragplot config_file
Processing reference genome: MAG_1113
Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqcrinke/bin/fragrecruit/fragrecruit-master/fragplot", line 326, in <module>
    contigs.append([seq.name.split('|')[3], len(seq.seq)])
IndexError: list index out of range


It seems the script is not functional, and there is no support ;-(

**Comment by mstrosaker** [comment]
The referenced line of code (326 in fragplot) is attempting to retrieve the contig IDs from the FASTA file for the reference genome.  When I wrote the script, sequences in reference genomes were identified like the following:

``>gi|260583424|ref|NZ_GG703805.1| Granulicatella elegans ATCC 700633 genomic scaffold supercont1.1, whole genome shotgun sequence``

The effect of that line of code is to extract ``NZ_GG703805.1`` as the contig ID for the corresponding sequence.  That format for FASTA files is the standard for sequences in GenBank, or, at least, it was a few years ago.

What is the first line in bacillus_anthracis_strain_k1_final_asm.fasta?  If the contig IDs are encoded in the FASTA file in a machine-parsable manner, I can probably help you modify fragplot to read it correctly.

**Comment by mstrosaker** [comment]
Wow... I just noticed that this is an old issue.  My apologies; I never got a notification when the issue was opened, only when tvtv195 commented on it.

**Comment by JemmaSun** [comment]
Hi mstrosaker,

I noticed that the way you calculated the quality score/identity is by looking for MD tag in QUAL field. I am wondering why use MD tag rather than mapping quality (field 5) to obtain the final score?
Also, usually there are a lot of entries in a sam file that only show AS tag and no MD tag, but their mapping quality is also good. Shouldn't we consider these sequences into our fragment recruitment result? Thank you.

**Comment by Thomieh73** [comment]
Hi Sorry for the slow response from my side, but the topic was of my desk at some point.

Now I am closing this issue in an attempt to clean up my own issue list.
best
Thomas
