### ISSUE TITLE
Calculating identity

### ISSUE THREAD

**Issue by JemmaSun** [mstrosaker/fragrecruit#2]
Hi mstrosaker,

I noticed that the way you calculated the quality score/identity is by looking for MD tag in QUAL field. I am wondering why use MD tag rather than mapping quality (field 5) to obtain the final score?
Also, usually there are a lot of entries in a sam file that only show AS tag and no MD tag, but their mapping quality is also good. Shouldn't we consider these sequences into our fragment recruitment result? Thank you.

**Comment by mstrosaker** [comment]
Hello, JemmaSun:

I have not looked into the SAM file format in a long time.  You are referring to the mapping quality (MAPQ) field, if I understand correctly, which describes the probability of a read being misplaced.  The objective of this project was to plot the identity of the aligned reads, not the mapping quality.  It likely wouldn't be too difficult to modify the code to use mapping quality instead, if you wanted.  Look at line 362 in fragplot; the plotter.add_point line is responsible for adding new points to the plot.  Replace frag.identity with the contents of the MAPQ field, or whatever else you'd like.

If your aligner doesn't add MD fields, you can use samtools to postprocess your SAM files to add them.  The command would look something like: "samtools fillmd -S file.sam genomic.fna > file.md.sam"

**Comment by JemmaSun** [comment]
Hi mstrosaker,

I am still wondering why use MD tag ('MD:Z:', line 35 in SAM_parser.py) only when calculating identity, not others such as 'AS:', 'XS:', etc.?  Thank you!

**Comment by mstrosaker** [comment]
All the information needed to calculate percent identity is in the CIGAR string provided in the MD tag.  Identity is defined as:

identity = 100 * (matches / (matches + mismatches))

For example, the string "MD:Z:27A5G2T6G4T1A6T2C0A7A1A0A0C0G1G1A5" demonstrates the presence of 68 matched nucleotides in an overall string of 84, yielding 81% identity.

**Comment by JemmaSun** [comment]
Thanks mstrosaker!

**Comment by mstrosaker** [comment]
Glad I could help!
